-- WITH FIRST_VISIT AS (SELECT CUSTOMER_ID, MIN(ORDER_DATE) as FIRST_VISIT_DATE
-- FROM CUSTOMER_ORDERS
-- GROUP BY CUSTOMER_ID) 
-- ,VISIT_FLAG AS 
-- (SELECT CO.*,FV.FIRST_VISIT_DATE
-- ,CASE WHEN CO.ORDER_DATE=FV.FIRST_VISIT_DATE THEN 1 ELSE 0 END AS FIRST_VISIT_FLAG
-- ,CASE WHEN CO.ORDER_DATE!=FV.FIRST_VISIT_DATE THEN 1 ELSE 0 END AS REPEAT_VISIT_FLAG
-- FROM CUSTOMER_ORDERS CO
-- INNER JOIN FIRST_VISIT FV ON CO.CUSTOMER_ID=FV.CUSTOMER_ID
-- )
-- SELECT ORDER_DATE,SUM(FIRST_VISIT_FLAG) AS NO_OF_NEW_CUSTOMERS,
-- SUM(REPEAT_VISIT_FLAG) AS NO_OF_REPEAT_CUSTOMERS
-- FROM VISIT_FLAG GROUP BY ORDER_DATE;

WITH FIRST_VISIT AS (SELECT CUSTOMER_ID, MIN(ORDER_DATE) as FIRST_VISIT_DATE
FROM CUSTOMER_ORDERS
GROUP BY CUSTOMER_ID) 
SELECT CO.ORDER_DATE
,SUM(CASE WHEN CO.ORDER_DATE=FV.FIRST_VISIT_DATE THEN 1 ELSE 0 END) AS FIRST_VISIT_FLAG
,SUM(CASE WHEN CO.ORDER_DATE!=FV.FIRST_VISIT_DATE THEN 1 ELSE 0 END) AS REPEAT_VISIT_FLAG
FROM CUSTOMER_ORDERS CO
INNER JOIN FIRST_VISIT FV ON CO.CUSTOMER_ID=FV.CUSTOMER_ID
GROUP BY CO.ORDER_DATE;



